### PR TITLE
More options for SASS

### PR DESCRIPTION
**Pull request by CupOfTea696**
Makes all the styles configurable.

### CODE REVIEW

**Comment by geddski** [comment]
thanks @CupOfTea696! This will be a great improvement. Could you check why the tests are failing? `npm run test` Thanks!

**Comment by geddski** [comment]
@CupOfTea696 nevermind they're passing now, must have been on the wrong branch. I'll review this shortly.

**Comment by CupOfTea696** [comment]
Maybe it was an earlier bug? Because I've noticed and fixed a few after I made the pull request.
Either way, you're welcome :)

**Comment by geddski** [comment]
@CupOfTea696 landed in 1.3.2. I squashed the commits down to a single commit. Thanks for all your hard work!

**Comment by geddski** [comment]
P.S. I love the forward slash for parts. Considering making that the default. What do you think?

**Comment by geddski** [comment]
FYI I just added this same behavior to the postcss version.

**Comment by CupOfTea696** [comment]
You're more than welcome! I absolutely love using CSStyle :)

Yeah, the forward slash really give me a feel of OOP, or at least OOP in PHP. 
However, I do think changing the default might result in some people updating csstyle in current projects and then having to change all of their html, so that's something to be considered.

Also, I noticed that my latest commits haven't been included yet, those ones that automate the character escaping, so you don't have to include escape characters in the setting vars anymore.

**Pull request closed without merging**
